### ISSUE TITLE
Multi language support

### ISSUE THREAD

**Issue by codehz** [Cirru/calcit-editor#18]
Is it possible to support other language that using s-exp like Scheme?

**Comment by jiyinyiyong** [comment]
Possible in theory, but you would need to fork project and add lots of code. There are things you need to reimplement based on my memory:

* For Clojure I use https://github.com/Cirru/sepal.clj/ to generate code and it's bundled inside Calcit as a dependency. You would need one for Scheme.
* Calcit assumes that imported variables are defined in `(ns)` with `:as` and `:refer`. Like going to definitions and renaming variables. It could be complicated for Scheme. I have too less knowledge for that.
* Another assumption in Calcit is that the whole language can be represented with data like `["a" ["b" "c"]]`, vectors and strings. So Calcit only supports a subset of Clojure syntax. It would be a subset too for Scheme.

Calcit itself does not intend to support other languages.
