### ISSUE TITLE
能不能画一个diagram来标示所有editor的部分？

### ISSUE THREAD

**Issue by stardiviner** [Cirru/calcit-editor#2]
虽然看了演示视频，但是咋一上手还是没法适应，可能是基础理解逻辑的缺失，要是题叶能补上就好多了。
- [ ] 比如node是啥，token是啥
- [ ] 比如按键要怎么操作来编写代码的示例
- [ ] editor里显示的结构和s-expression相对应的结构是什么样的关系

**Comment by jiyinyiyong** [comment]
嗯, 很多信息是缺失的.. 不知道做多少才能补完...

> 比如node是啥，token是啥

Cirru 的数据格式简单来说就是数组和字符串的嵌套组合, 其中 token 指得是字符串对应的叶子节点, 而数组会被称为表达式 expression. 两者都可以被叫做 node.

>  比如按键要怎么操作来编写代码的示例

好像针对每个操作做视频工作量很大啊 >.< 现在只有[快捷键列表](https://github.com/Cirru/respo-cirru-editor/wiki/Keyboard-Shortcuts), 术语有点随意.

> editor里显示的结构和s-expression相对应的结构是什么样的关系

Editor 上的样式是经过定制的, 实际上要看 DOM 结构才更明显, 一个 DOM 就是一个 expression, 一个字符串用一个 `<input>`. 可能打开 Element Inspector 在 `.cirru-expression` 上加 `border-width:1px` 会看得更清晰. 看这里的例子 http://cirru.org/
