### ISSUE TITLE
能不能加个GUI的视图.. 类似node-red那种积木

### ISSUE THREAD

**Issue by BlankRain** [Cirru/calcit-editor#20]
通过在编辑器里编辑.
可以看见可视化后的代码树.

**Comment by jiyinyiyong** [comment]
长远规划来说是有的, Canvas 绘制树形的布局发挥的余地比较多, 特别是未来考虑在 AR 设备当中的通过键盘意外的设备来编写代码的场景.

目前来说没有时间深入了解 Canvas 绘制等等细节, 短期不会尝试类似功能.

单纯从可视化的角度来说的话, `calcit.edn` 文件可以被其他程序解析, 然后自定义渲染规则, 比如 http://github.com/Cirru/calcit-viewer
